#runtime: java
#env: flex
##runtime_config:
##  jdk: openjdk8
#env_variables:
#  SPRING_PROFILES_ACTIVE: "gcp,mysql"
#handlers:
#  - url: /.*
#    script: this field is required, but ignored
#resources:
#  cpu: 1
#  memory_gb: 1
#  disk_size_gb: 8
#  volumes:
#    - name: ramdisk1
#      volume_type: tmpfs
#      size_gb: 0.5
#manual_scaling:
#  instances: 1


runtime: java
env: flex

handlers:
  - url: /.*
    script: this field is required, but ignored


automatic_scaling:
  min_num_instances: 1
  max_num_instances: 7
